default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://opensend:opensend_dev@localhost:5432/opensend_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://opensend:opensend_dev@localhost:5432/opensend_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || ENV["POSTGRES_URL"] %>
